package com.example.mkb_employee_bot.entiry.enums;

public enum Stage {
    STARTED(1),
    LANGUAGE_SELECTED(2),
    CONTACT_SHARED(3),
    CONTACT_SET(4),
    ROLE_IDENTIFIED(0),
    SECTION_SELECTED(5),
    DEPARTMENT_SELECTED_FOR_EMPLOYEE_INFO(),
    DEPARTMENT_SELECTED_FOR_DELETING(),
    DEPARTMENT_SELECTED_FOR_UPDATING(),
    DEPARTMENT_SELECTED_FOR_CREATING_MANAGEMENT(),
    ENTER_NAME_FOR_UPDATE_DEPARTMENT(),

    ENTER_NAME_FOR_CREATE_MANAGEMENT(),
    MANAGEMENT_SELECTED_FOR_DELETING(),
    MANAGEMENT_SELECTED_FOR_UPDATING(),
    DEPARTMENT_SELECTED_FOR_UPDATING_MANAGEMENT(),
    MANAGEMENT_SELECTED_FOR_EMPLOYEE_INFO(),
    POSITION_SELECTED_FOR_EMPLOYEE_INFO(),
    DEPARTMENT_EMPLOYEE_SELECTED(),
    ENTERED_EMPLOYEE_NAME_FOR_SEARCH_ROLE_USER(),
    SELECTED_EMPLOYEE_NAME_FOR_SEARCH_ROLE_USER(),
    ENTER_EMPLOYEE_NAME_ROLE_ADMIN(),
    ENTER_EMPLOYEE_BIRTHDATE_ROLE_ADMIN,
    ENTER_EMPLOYEE_PHONE_NUMBER_ROLE_ADMIN,
    ENTER_EMPLOYEE_ADDITIONAL_PHONE_NUMBER_ROLE_ADMIN,
    ENTER_NAME_FOR_CREATE_DEPARTMENT,
    SELECT_POSITION_DEPARTMENT,
    ENTER_EMPLOYEE_POSITION_ROLE_ADMIN,
    SELECT_EDUCATION_TYPE,
    ENTER_EDUCATION,
    SELECT_FILE_TYPE,
    ENTER_SKILLS,
    SHARE_ATTACHMENT;


    private int value;

    Stage(int value) {
        this.value = value;
    }

    Stage() {}

    public int getValue() {
        return value;
    }
}