package com.example.mkb_employee_bot.entiry.enums;

public enum Stage {
    START,
    SELECT_LANGUAGE,
    SHARE_CONTACT,
    CLARIFICATION_ROLE,
    ENTER_EMPLOYEE_NAME_ROLE_ADMIN,
    ENTER_EMPLOYEE_BIRTHDATE_ROLE_ADMIN,
    ENTER_EMPLOYEE_PHONE_NUMBER_ROLE_ADMIN,
    ENTER_EMPLOYEE_ADDITIONAL_PHONE_NUMBER_ROLE_ADMIN,
    SELECT_POSITION_DEPARTMENT,
    ENTER_EMPLOYEE_POSITION_ROLE_ADMIN,
    SELECT_EDUCATION_TYPE,
    ENTER_EDUCATION,
    SELECT_FILE_TYPE,
    SHARE_ATTACHMENT,
    ENTER_SKILLS;
}